version: v1-winbuild-{build}

image: Visual Studio 2019

platform:
  - Win32
  - x64

environment:
  vspath: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community'

configuration:
  - Release
  
skip_commits:
  message: /workflows/
  files:
    - '.github/**'

build_script:
  - cd build
  - cpack
